### ISSUE TITLE
Use Flexbox instead of float for .message and use flexbox for .chat-box to position messages instead

### ISSUE THREAD

**Issue by AVGVSTVS96** [AVGVSTVS96/flaskGPT#10]
```css
/* Remove float from .message and use flexbox for .chat-box */
.chat-box {
  display: flex;
  flex-direction: column;
  align-items: flex-end;
  flex-grow: 1;
  width: 100%;
  min-height: 100px;
  margin-bottom: 20px;
  overflow-y: auto;
  padding-right: 10px;
  max-width: calc(100% - 10px);
}

.user-message {
  align-self: flex-end;
}

.assistant-message {
  align-self: flex-start;
}
```
